version: "3.8"



services:

  okr-db:
    container_name: okr-db
    hostname: okr-db
    networks:
      - backnet
    image: postgres:16.1
    restart: on-failure
    volumes:
      - okr-db:/var/lib/postgresql/data
      - ./init/OKR-DB/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql:ro
      - ./init/OKR-DB/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: okr-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  okr-service:
    container_name: okr-service
    hostname: okr-service
    networks:
      - backnet
    build:
      context: ./okrservice
      dockerfile: Dockerfile
    image: epro_project-okr-service
    restart: on-failure
    depends_on:
      okr-db:
        condition: service_healthy
    ports:
      - "8081:8081"


volumes:
  okr-db:

networks:
  backnet:
  frontnet:





