

CREATE SEQUENCE Company_ID_seq START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE BusinessUnit_ID_seq START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE Unit_ID_seq START WITH 1000 INCREMENT BY 1;

-- CREATE SEQUENCE Role_ID_seq START WITH 1000 INCREMENT BY 1;
-- CREATE SEQUENCE Privilege_ID_seq START WITH 1000 INCREMENT BY 1;

CREATE SEQUENCE Objective_ID_seq START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE KeyResult_ID_seq START WITH 1000 INCREMENT BY 1;

CREATE SEQUENCE User_ID_seq START WITH 1000 INCREMENT BY 1;





-- Company and Unit

CREATE TABLE tbl_Company
(
  Name VARCHAR(100) NOT NULL,
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE tbl_BusinessUnit
(
  Name VARCHAR(100) NOT NULL,
  ID BIGINT NOT NULL,
  Company_ID BIGINT NOT NULL,
  PRIMARY KEY (ID, Company_ID),
  FOREIGN KEY (Company_ID) REFERENCES tbl_Company(ID) 
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);

CREATE TABLE tbl_Unit
(
  Name VARCHAR(100) NOT NULL,
  ID BIGINT NOT NULL,
  BusinessUnit_ID BIGINT NOT NULL,
  Company_ID BIGINT NOT NULL,
  PRIMARY KEY (ID, BusinessUnit_ID, Company_ID),
  FOREIGN KEY (BusinessUnit_ID, Company_ID) REFERENCES tbl_BusinessUnit(ID, Company_ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);





-- User

CREATE TABLE tbl_User
(
  Username VARCHAR(100) NOT NULL,
  Password VARCHAR(100) NOT NULL,
  Email VARCHAR(100) UNIQUE NOT NULL,
  Surname VARCHAR(100) NOT NULL,
  Firstname VARCHAR(100) NOT NULL,
  ID BIGINT NOT NULL,
  Company_ID BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (Company_ID) REFERENCES tbl_Company(ID)
    ON DELETE SET NULL 
    ON UPDATE CASCADE
);

CREATE TABLE tbl_Company_employs_User
(
  User_ID BIGINT,
  Company_ID BIGINT,
  PRIMARY KEY (User_ID, Company_ID),
  FOREIGN KEY (User_ID) REFERENCES tbl_User(ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (Company_ID) REFERENCES tbl_Company(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);








-- Objective

CREATE TABLE tbl_Objective
(
  Deadline TIMESTAMP NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Description VARCHAR(200) NOT NULL,
  ID BIGINT NOT NULL,
  User_ID BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (User_ID) REFERENCES tbl_User(ID)
    ON DELETE SET NULL 
    ON UPDATE CASCADE
);

CREATE TABLE tbl_CompanyObjective
(
  Objective_ID BIGINT NOT NULL,
  Company_ID BIGINT NOT NULL,
  PRIMARY KEY (Objective_ID),
  FOREIGN KEY (Objective_ID) REFERENCES tbl_Objective(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (Company_ID) REFERENCES tbl_Company(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);

CREATE TABLE tbl_BusinessUnitObjective
(
  Objective_ID BIGINT NOT NULL,
  Company_ID BIGINT NOT NULL,
  BusinessUnit_ID BIGINT NOT NULL,
  PRIMARY KEY (Objective_ID),
  FOREIGN KEY (Objective_ID) REFERENCES tbl_Objective(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (BusinessUnit_ID, Company_ID) REFERENCES tbl_BusinessUnit(ID, Company_ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);




-- Role and Privilege

CREATE TABLE tbl_Role
(
  Name VARCHAR(100) UNIQUE NOT NULL,
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE tbl_Privilege
(
  Name VARCHAR(100) UNIQUE NOT NULL,
  ID BIGINT NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE tbl_Role_includes_Privilege
(
  Role_ID BIGINT NOT NULL,
  Privilege_ID BIGINT NOT NULL,
  PRIMARY KEY (Role_ID, Privilege_ID),
  FOREIGN KEY (Role_ID) REFERENCES tbl_Role(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (Privilege_ID) REFERENCES tbl_Privilege(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);

CREATE TABLE tbl_Role_inherits_Role
(
  Role_ID BIGINT NOT NULL,
  Inherit_ID BIGINT NOT NULL,
  PRIMARY KEY (Role_ID, Inherit_ID),
  FOREIGN KEY (Role_ID) REFERENCES tbl_Role(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (Inherit_ID) REFERENCES tbl_Role(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);



CREATE TABLE tbl_RoleAssignment
(
  User_ID BIGINT NOT NULL,
  Role_ID BIGINT NOT NULL,
  Company_ID BIGINT NOT NULL,
  PRIMARY KEY (User_ID, Role_ID, Company_ID),
  FOREIGN KEY (User_ID) REFERENCES tbl_User(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (Role_ID) REFERENCES tbl_Role(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (Company_ID) REFERENCES tbl_Company(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);




-- KeyResult

CREATE TABLE tbl_KeyResultType
(
  Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (Name)
);

CREATE TABLE tbl_KeyResult
(
  Goal INT NOT NULL,
  Type_Name VARCHAR(100) NOT NULL,
  Title VARCHAR(100) NOT NULL,
  Description VARCHAR(200) NOT NULL,
  Current INT NOT NULL,
  ConfidenceLevel INT NOT NULL,
  ID BIGINT NOT NULL,
  Objective_ID BIGINT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (Objective_ID) REFERENCES tbl_Objective(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE, 
  FOREIGN KEY (Type_Name) REFERENCES tbl_KeyResultType(Name)
    ON DELETE CASCADE
);
CREATE TABLE tbl_BusinessUnitKeyResult
(
  KeyResult_ID BIGINT NOT NULL,
  PRIMARY KEY (KeyResult_ID),
  FOREIGN KEY (KeyResult_ID) REFERENCES tbl_KeyResult(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);
CREATE TABLE tbl_CompanyKeyResult
(
  KeyResult_ID BIGINT NOT NULL,
  PRIMARY KEY (KeyResult_ID),
  FOREIGN KEY (KeyResult_ID) REFERENCES tbl_KeyResult(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);



CREATE TABLE tbl_KeyResultUpdate
(
  StatusUpdate VARCHAR(100) NOT NULL,
  Timestamp TIMESTAMP NOT NULL,
  KeyResult_ID BIGINT NOT NULL,
  Old_KeyResult_ID BIGINT NOT NULL,
  New_KeyResult_ID BIGINT NOT NULL,
  User_ID BIGINT NOT NULL,
  PRIMARY KEY (KeyResult_ID, Old_KeyResult_ID),
  FOREIGN KEY (KeyResult_ID) REFERENCES tbl_KeyResult(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (Old_KeyResult_ID) REFERENCES tbl_KeyResult(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (New_KeyResult_ID) REFERENCES tbl_KeyResult(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (User_ID) REFERENCES tbl_User(ID)
    ON DELETE SET NULL 
    ON UPDATE CASCADE
);





CREATE TABLE tbl_Unit_contributes_KeyResult
(
  Unit_ID BIGINT NOT NULL,
  BusinessUnit_ID BIGINT NOT NULL,
  Company_ID BIGINT NOT NULL,
  KeyResult_ID BIGINT NOT NULL,
  PRIMARY KEY (Unit_ID, BusinessUnit_ID, Company_ID, KeyResult_ID),
  FOREIGN KEY (Unit_ID, BusinessUnit_ID, Company_ID) REFERENCES tbl_Unit(ID, BusinessUnit_ID, Company_ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (KeyResult_ID) REFERENCES tbl_KeyResult(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);
CREATE TABLE tbl_BusinessUnit_contributes_KeyResult
(
  BusinessUnit_ID BIGINT NOT NULL,
  Company_ID BIGINT NOT NULL,
  KeyResult_ID BIGINT NOT NULL,
  PRIMARY KEY (BusinessUnit_ID, Company_ID, KeyResult_ID),
  FOREIGN KEY (BusinessUnit_ID, Company_ID) REFERENCES tbl_BusinessUnit(ID, Company_ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (KeyResult_ID) REFERENCES tbl_KeyResult(ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);







CREATE TABLE tbl_CompanyKeyResult_represents_BusinessUnitObjective
(
  CompanyKeyResult_ID BIGINT NOT NULL,
  BusinessUnitObjective_ID BIGINT NOT NULL,
  PRIMARY KEY (CompanyKeyResult_ID),
  FOREIGN KEY (CompanyKeyResult_ID) REFERENCES tbl_CompanyKeyResult(KeyResult_ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE,
  FOREIGN KEY (BusinessUnitObjective_ID) REFERENCES tbl_BusinessUnitObjective(Objective_ID)
    ON DELETE CASCADE 
    ON UPDATE CASCADE
);


