server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://okr-db:5432/okr-db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      format_sql: true

